"""test running migrations

Revision ID: 1def7a0a9abd
Revises: 845230f20f5b
Create Date: 2023-07-28 00:15:09.010246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1def7a0a9abd'
down_revision = '845230f20f5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
