"""test running migrations

Revision ID: 472262c5756e
Revises: 1def7a0a9abd
Create Date: 2023-07-28 00:18:59.658501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472262c5756e'
down_revision = '1def7a0a9abd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
