"""test running migrations

Revision ID: 845230f20f5b
Revises: 1208c59e183b
Create Date: 2023-07-28 00:14:15.207102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845230f20f5b'
down_revision = '1208c59e183b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
